### ISSUE TITLE
2021-02-05 Sprint

### ISSUE THREAD

**Issue by ameyrk99** [SrDesignLEDBoard/super-board#24]
- [x] Update the documents (Stuff like single button, etc) [super-board-docs#4](https://github.com/SrDesignLEDBoard/super-board-docs/issues/4) @tasnim99 
- [ ] Create website from a template or scratch [srdesignledboard.github.io#2](https://github.com/SrDesignLEDBoard/srdesignledboard.github.io/issues/2) @mahipalyadav 
- [ ] Print the 3D frame @ememeti 
- [ ] Soder the rest of the components @ameyrk99 @Ash557 
- [ ] NBA #11 @Ash557 
- [ ] MLB #12 @ememeti 
- [ ] Soccer #13 @tasnim99
- [ ] Yellow LEDs #21 @ameyrk99 
- [ ] Dependencies #23 @ameyrk99
