### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ameyrk99** [SrDesignLEDBoard/super-board#40]
- [x] Making the website (public)
- [x] Code for the blog
- [x] Button control (power and control button) software part
- [x] Tie all the leagues together with the buttons
- [x] Poster for the class
- [x] Include animations for live games
- [x] Update the images for NBA and La Liga
- [x] Create a demo
- [x] Create a manual or a guide for installation
- [x] Documenting the code with doxygen (HTML)
